--ADDING PRODUCT INTO MANAGE PRODUCT TABLE
CREATE OR REPLACE PROCEDURE ADD_PRODUCT(PRODUCT_NAME VARCHAR2,
                                        UNIT NUMBER,
                                        PRISE_PE_UNIT FLOAT)
AS
BEGIN
    INSERT INTO MANAGE_PRODUCT VALUES (SQN_PRODUCT_ID.NEXTVAL*100,PRODUCT_NAME,UNIT,PRISE_PE_UNIT);
END;

SELECT * FROM MANAGE_PRODUCT;

EXEC ADD_PRODUCT (PRODUCT_NAME=>'MUSTERD SEED',UNIT=>2,PRISE_PE_UNIT=>120);
/

--IT IS USED TO MANGE ORDER TABLE
CREATE OR REPLACE PROCEDURE P_ORDER (CUSTOMER VARCHAR2)
AS
BEGIN
    INSERT INTO ORDER_MANAGE VALUES(SQN_ORDER_ID.NEXTVAL,SYSTIMESTAMP,CUSTOMER,0) ;

    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(20001,'SOME THING IS WRONG'); 
END;

SELECT * FROM ORDER_MANAGE;

EXEC P_ORDER(CUSTOMER=>'PABITRA KUMAR PATRO');
/

--IT IS FOR MANAGE ORDER DEATELS TABLE
CREATE OR REPLACE PROCEDURE P_ORDER_DEATELS(P_PRODUCT_ID NUMBER,
                                            QUANTITY FLOAT)
                                                            
AS
TOTAL FLOAT;
SUM_OF_COST FLOAT;
CURVAL NUMBER;
BEGIN
    SELECT PRISE_PE_UNIT * QUANTITY INTO TOTAL FROM MANAGE_PRODUCT WHERE PRODUCT_ID=P_PRODUCT_ID;

    SELECT SQN_ORDER_ID.CURRVAL  INTO CURVAL FROM DUAL;

    INSERT INTO ORDER_DEATELS VALUES(SQN_ORDER_ID.CURRVAL,P_PRODUCT_ID,QUANTITY,TOTAL);

    SELECT SUM(TOTAL_PRISE) INTO SUM_OF_COST FROM ORDER_DEATELS WHERE ORDER_ID=CURVAL;

    UPDATE ORDER_MANAGE SET TOTAL_PRISE=SUM_OF_COST WHERE ORDER_ID=CURVAL;

    EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(20002,'SOMETHING IS WRONG');
END;

EXEC P_ORDER_DEATELS(P_PRODUCT_ID=>200,QUANTITY=>2);
/
--IT IS FOR PRINT BILL
CREATE OR REPLACE PROCEDURE PRINT_BILL(DET OUT SYS_REFCURSOR)
AS
CURVAL NUMBER;
BEGIN
SELECT MAX(ORDER_ID) INTO CURVAL FROM CUSTOMER_ALL_DEATELS;
    OPEN DET FOR SELECT * FROM CUSTOMER_ALL_DEATELS WHERE ORDER_ID=CURVAL;

    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ENTER VALID ID ');
END PRINT_BILL;

