--CREATION OF TABLE
CREATE TABLE MARK_OF_UNIT (UNIT VARCHAR2(10),
                            IDENTIFIERS NUMBER CONSTRAINT IDT_UNK UNIQUE
);

CREATE TABLE MANAGE_PRODUCT (PRODUCT_ID NUMBER CONSTRAINT ID_PK PRIMARY KEY,
                             PRODUCT_NAME VARCHAR2(50),
                             UNIT NUMBER CONSTRAINT UNIT_FK REFERENCES MARK_OF_UNIT(IDENTIFIERS),
                             PRISE_PE_UNIT FLOAT CONSTRAINT PRICE_NN NOT NULL
);

CREATE TABLE ORDER_MANAGE (ORDER_ID NUMBER CONSTRAINT OID_PK PRIMARY KEY,
                           DATES DATE CONSTRAINT DT_NN NOT NULL,
                           COSTOMER_NAME VARCHAR2(50) CONSTRAINT CST_NN  NOT NULL,
                           TOTAL_PRISE FLOAT CONSTRAINT TP_NN NOT NULL
);

CREATE TABLE ORDER_DEATELS (ORDER_ID NUMBER CONSTRAINT ORD_FK REFERENCES ORDER_MANAGE(ORDER_ID),
                            PRODUCT_ID NUMBER CONSTRAINT PRDID__FK REFERENCES MANAGE_PRODUCT(PRODUCT_ID),
                            QUANTITY FLOAT CONSTRAINT QNT_NN NOT NULL,
                            TOTAL_PRISE FLOAT CONSTRAINT TOP_NN NOT NULL
);
/
--CREATE SEQUENCE FOR AUTO INCREMENT
CREATE SEQUENCE SQN_PRODUCT_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 10; -- IT IS FOR GENARATING PRODUCT ID

CREATE SEQUENCE SQN_ORDER_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 10; --IT IS FOR GENARATING ORDER ID
/

--CREATE VIEW FOR SHOW ALL DEATELS
CREATE VIEW CUSTOMER_ALL_DEATELS
AS
SELECT T2.COSTOMER_NAME,
T2.ORDER_ID,
T2.DATES,
T1.PRODUCT_NAME,
T1.PRODUCT_ID,
T3.QUANTITY||' '||T4.UNIT AS QUANTITY,
T3.TOTAL_PRISE,
T1.PRISE_PE_UNIT

FROM MANAGE_PRODUCT T1 JOIN ORDER_DEATELS T3 ON T1.PRODUCT_ID=T3.PRODUCT_ID
                                JOIN ORDER_MANAGE T2 ON T3.ORDER_ID=T2.ORDER_ID 
                                JOIN MARK_OF_UNIT T4 ON T4.IDENTIFIERS=T1.UNIT
                                ORDER BY T2.ORDER_ID;



SELECT * FROM CUSTOMER_ALL_DEATELS;


