SELECT * FROM MARK_OF_UNIT T4;
SELECT * FROM MANAGE_PRODUCT T1;
SELECT * FROM ORDER_MANAGE T2;
SELECT * FROM ORDER_DEATELS T3;

CREATE OR REPLACE PROCEDURE PRINT_BILL(P_ORDER_ID NUMBER)
AS
    DET SYS_REFCURSOR;
    V CUSTOMER_ALL_DEATELS%ROWTYPE;
BEGIN
    OPEN DET FOR SELECT C1.* FROM CUSTOMER_ALL_DEATELS C1 ORDER BY ORDER_ID;
    LOOP
        FETCH DET INTO V;
        EXIT WHEN DET%NOTFOUND;

        IF V.ORDER_ID = P_ORDER_ID THEN
            DBMS_OUTPUT.PUT_LINE(V.COSTOMER_NAME);
        ELSE    
            DBMS_OUTPUT.PUT_LINE(' ');
        END IF;
    END LOOP; 
END;
/
SET SERVEROUTP ON;
EXEC PRINT_BILL(3);
/
CREATE OR REPLACE PROCEDURE PRINT_BILL(P_ORDER_ID NUMBER)
AS
TYPE TP IS TABLE OF VARCHAR2(50);
V TP:=TP(NULL,NULL,NULL,NULL);
BEGIN
   SELECT COSTOMER_NAME,ORDER_ID,DATES
   INTO 
   V(1),V(2),V(3)
   FROM CUSTOMER_ALL_DEATELS WHERE ROWNUM<=1 AND ORDER_ID=P_ORDER_ID;
   DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME :-'||V(1));
   DBMS_OUTPUT.PUT_LINE('ORDER ID :-'||V(2));
   DBMS_OUTPUT.PUT_LINE('DATE :-'||V(3));
   DBMS_OUTPUT.PUT_LINE('TOTAL COST :-'||V(4));
   DBMS_OUTPUT.PUT_LINE(' ');
   DBMS_OUTPUT.PUT_LINE('DEATELS');
   DBMS_OUTPUT.PUT_LINE('___________________');
END;

EXEC PRINT_BILL(3);